Some fixes :-)
aangiel/clojuredart-material-cupertino pull request #1
Opened 2023-06-13 18:40 UTC by dupuchba

2023-06-13 19:14 UTC, aangiel reviewed
I'm very proud of myself that the Creator has only few small fixes :D Thanks!

2023-06-13 19:14 UTC, aangiel commented on src/acme/main.cljd
> +    .children (drawer-children context)))
To be honest, I prefer my formatting. It lines up properties and indents them as be owned by w/ListView

2023-06-13 19:14 UTC, aangiel commented on src/acme/main.cljd
> +(def ^:private ^c/CupertinoThemeData darkDefaultCupertinoTheme
Why we need that?

2023-06-13 19:14 UTC, aangiel commented on src/acme/main.cljd
> +        .brightness d/Brightness.dark
Is this only for convention that namespaces is always followed by slash?

2023-06-13 19:18 UTC, aangiel commented on src/acme/main.cljd
> +(def ^:private ^c/CupertinoThemeData darkDefaultCupertinoTheme
Ok, that's clear after #clojuredart Slack channel message that it removes dynamic warning.

2023-06-14 07:11 UTC, dupuchba commented on src/acme/main.cljd
> +    .children (drawer-children context)))
no problem!

2023-06-14 07:12 UTC, dupuchba commented on src/acme/main.cljd
> +        .brightness d/Brightness.dark
we support both but it's also simpler to use this form when try to get nested property like so
`m/Colors.grey.shade100`

2023-06-14 07:57 UTC, aangiel requested changes
@dupuchba could you rollback commented formatting changes?

2023-06-14 08:42 UTC, dupuchba commented
hey @aangiel unfortunately I am very busy today.
The idea of the PR was more to show you alternatives, there is no "truth" when it comes to writing code (although sometimes there is really bad code :D ) . Anyway just take what you want from this PR (or nothing).

2023-06-14 09:08 UTC, aangiel commented
@dupuchba Ok. Yeah, that's the point. Every code should be treated individually. Yes, I saw a looot of bad code (which was readable, but unmaintenable). 

You know, it's my first incoming PR :D So I treat it very serious :D 

I'm merging it, because it's very valuable. Thank you a lot!

2023-06-14 09:08 UTC, aangiel approved these changes

2023-06-14 09:08 UTC, merged